// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  DateTimeExpression = 1,
  FullYear = 4,
  MonthName = 6,
  NumericDayOfMonth = 8,
  DayOfMonthOrdinal = 9,
  MonthNumber = 11,
  TwoDigitYear = 17
