// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  DateTimeExpression = 1,
  FullYear = 4,
  MonthNameMaybeDot = 6,
  MonthNameAbbrev = 7,
  MonthNameFullExceptMay = 8,
  NumericDayOfMonth = 10,
  DayOfMonthOrdinal = 11,
  MonthName = 15,
  MonthNumber = 36,
  TwoDigitYear = 58,
  DayOfMonthYear = 95
