// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  DateTimeExpression = 1,
  Date = 2,
  FullYear = 3,
  MonthNameNoDot = 4,
  MonthNameFull = 5,
  MonthNameAbbrev = 6,
  DayOfMonth = 7,
  NthDayOfMonth = 8,
  DayOfMonthNum = 9,
  MonthNoDot = 10,
  MonthNum = 11,
  Month = 12,
  MonthName = 13,
  Year = 14,
  TwoDigitYear = 15
